services:
  mmdvm:
    image: ghcr.io/oe3anc/mmdvmhost:latest
    volumes:
      - mmdvmdata:/app/mmdvm/
      - /tmp/sql/sqlfile:/tmp/sql
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped

  filebrowser:
    image: tinyfilemanager/tinyfilemanager:master
    ports:
      - "8080:80"
    volumes:
      - mmdvmdata:/var/www/html/data
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
    restart: unless-stopped

volumes:
  filebrowser:
  mmdvmdata:
