services:
  mmdvm:
    image: oe3anc/mmdvmhost
    volumes:
      - mmdvmdata:/app/mmdvm/configs
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "8080:80"
    volumes:
      - filebrowser:/data
      - mmdvmdata:/srv
    restart: unless-stopped

volumes:
  filebrowser:
  mmdvmdata:
