services:
  mmdvm:
    image: ghcr.io/oe3anc/mmdvmhost:main
    volumes:
      - mmdvmdata:/app/mmdvm/
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "8080:80"
    volumes:
      - ./database.db:/database.db
      - mmdvmdata:/srv
    restart: unless-stopped

volumes:
  filebrowser:
  mmdvmdata:
