services:
  mmdvm:
    image: ghcr.io/oe3anc/mmdvmhost:main
    volumes:
      - mmdvmdata:/app/mmdvm/
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped

  filebrowser:
    image: tinyfilemanager/tinyfilemanager:master
    ports:
      - "8080:80"
    volumes:
      - mmdvmdata:/var/www/html/data
    restart: unless-stopped

volumes:
  filebrowser:
  mmdvmdata:
